# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e89182313fa16a12adc335bbe6e478102d0a03df4558f287a42a7e040882c596e87883ca9fdf37f461739e3e46369758e3a0af8fa239e248ceecb043d091f12

test:
  secret_key_base: 6428ff9efb4625ac97e3d8e160971228e775d677287a9d16841700d8a4f2d6f2923f10ee8d8f147f50fac5c47044a623a273791309c23013b6b65dd281820b14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
