# User account
user: sftp
welcome_msg: "Welcome, #{user_name}!"

# URL to API endpoint. Used for api calls. Should end with a slash.
api_url: "http://localhost:3000/"

# Storage path. Should end with a slash.
storage_path: "/home/sftp/storage/"

# Allowed commands
allowed_cmds: [sftp, scp, rsync, rdist, cvs]
