# SSH-enabled user
user: sftp

# Home directory of user
home_directory: "/home/sftp/"

# Root path of shares
storage_path: "/home/sftp/storage/"

# Time between scheduled disk usage recalculations
disk_usage_recalc_interval: "8.hours"

# Enable/disable features
features:
  # Enforce quotas
  quotas: false

  # Enforce at-rest encryption
  encryption: false

# sftp-shell
shell:
  # Log file location
  log: "/home/sftp/sftp-shell.log"

  # API endpoint URL
  api: "http://localhost:3000/"

  # Allowed commands
  allowed_cmds: [sftp, scp, rsync]
