# SSH-enabled user
user: florian

# Home directory of user
home_directory: "/home/florian/"

# Root path of shares
storage_path: "/home/florian/storage/"

# Time between scheduled disk usage recalculations
disk_usage_recalc_interval: "8.hours"

# Enable/disable features
features:
  # Enforce quotas
  quotas: false

  # Enforce at-rest encryption
  encryption: false

# sftp-shell
shell:
  # Log file location
  log: "/home/florian/sftp-shell.log"

  # API endpoint URL
  api: "http://localhost:3000/"
